### ISSUE TITLE
Is it possible to export all the mapping information from the "mapper" object?

### ISSUE THREAD

**Issue by kozo2** [egonw/BridgeDbR#2]
Thank you for closing the issue below. (BTW I can not see this issue. Can you check the "Issues" option of the following repo?)
https://github.com/bridgedb/bridgedb-r/issues/1

I succeeded in loading the latest metabolite bridge with the latest BridgeDbR.
```
mapper = loadDatabase("metabolites_20170826.bridge")
```

Next I tried to export all the mapping info to some sort of table.
However BridgeDbR does not seem to have such a function.

Is it possible to export all the mapping information from the mapper object (with BridgeDbR)?

**Comment by egonw** [comment]
The other tracker is no longer visible, because that repository is deprecated and I do not want people to file issues there anymore, but here instead... that's why.

**Comment by egonw** [comment]
Regarding the feature request... BridgeDb itself has a method to iterate over all mappings, so, technically it is possible...

**Comment by kozo2** [comment]
Thank you. I understood.
